# DATA STRUCTURES - Numpy, Scipy

## Numpy

Fajny cheat sheet do Nympy
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

### Tworzenie

```{python}

import numpy as np


#(1) z definicji

# jednowymiarowa macierz
np.array([1,2,3,4])

# tak jak przy DataFrames, tworzymy dwuwymiarową macierz podajac kolejno elementy wiersza a nie kolumny:
np.array( [[1,2], [3,4]] ) # wartosci 1 i 2 to bedzie pierwszy wiersza a nie kolumna

# wymusze typu danych (w przykladnie na typ 'string'
a = np.array([1,2,3], dtype='str') # UWAGA -to nie jest Pandas wiec tekst to nie typ 'object', ale tak jak w całym Pythonie 'str'

# macierz wielowymiarowa
a_w = np.array([[[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]]]) # macierz 3 wymiarowa (3x3x3 elementow)
a_w.ndim # macierz ma 3 wymiary






#(2) z listy

l1 = [1,2,3,4]
np.array(l)

l2 = [1, 'a']
a = np.array(l2) # macierz musi byc jednorodna pod wzgledem typu, wiec liczba 1 zostala przekonwertowana na tekst
a.dtype # typ U11 oznacza ze "All the elements got converted into a string"




#(3) z DataFrame

import pandas as pd
df = pd.DataFrame([[1,2],[3,4]], columns = ['A', 'B'])

# sposob 1
a1 = df.as_matrix(columns=['A', 'B']) # tutaj mozemy wybierac kolumny

# sposob 2
a2 = np.asmatrix(df, dtype = 'str') # tutaj jest mozliowosc wymuszenia typu


# sposob 3
a3 = np.asarray(df, dtype = 'str') # tutaj jest mozliowosc wymuszenia typu






#(4) tworzenie specyficznych macierzy
a = np.array([1,2,3,4])
np.zeros_like(a) # tworze macierz o takich samych rozmwiarach jak macierz 'a' ale wypelniam wszystko ZERAMI
np.ones_like(a) # tworze macierz o takich samych rozmwiarach jak macierz 'a' ale wypelniam wszystko JEDYNKAMI

np.empty(shape=[3,3], dtype='str') # utworzenie pustej tabeli typu 'str' (tekst)
np.empty(shape=[3,3], dtype='int') # utworzenie tabeli typu 'int' - bedzie wypelniona losowymi wartosciami

np.zeros(shape=[3,3]) # utworzenie pustej tabeli o wymiarach 3X3 wypelnionej zerami
np.ones(shape=[3,3]) # utworzenie pustej tabeli o wymiarach 3X3 wypelnionej jedynkami

np.full(shape=[3,3], fill_value=10) # utworzenie pustej tabeli o wymiarach 3X3 wypelnionej liczba 10.

df = pd.DataFrame([[1,2],[3,4]], columns = ['A', 'B'])
np.array([None for _ in range(df.shape[0])]) # vektor wypelniony 'None' o ilosci wierszy w ramce 'df'




```



### atrybuty
 
Macierze przechowuja dane jednorodne. W macierze (w przeciwienstwie np. do list) nie moze byc dwoch typow danych na raz (np. liczba i tekst)

```{python}
import numpy as np

#(1) jednorodnosc typu

# jezeli kolumny sa roznego typu to tak jak przy pistach sie je ujednoradnia
df2 = pd.DataFrame([[1,'2'],[3,'4']]) # pierwsza kolumna to liczba a druga to tekst
a2 = df2.as_matrix() # wszystko zostal zamienione na tekst
a2[:,0] # podglad pierwszej kolumny przekonwertowanej na tekst


#(2) inne atrybuty

a = np.array([[1,2],[3,4]])

a.ndim # ilosc wymiarow

a.shape # rozmiary

a.size # ilosc elementow

a.dtype # typ przechowywanych danych






```


### odwolywanie sie przez indeksy

Dla macierzy jednowymiarowych sytuacja jest tak jak przy listach.

Macierze dwuwymiarowe
```{python}

# tworze macierz o wymiarach 4x3 (4 wiersze, 3 kolumny)
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

a[1,1]# piersze komorka (pierwszy wiersz, pierwsza kolumn)
a[:,0] # pierwsza kolumna
a[0,:] # pierwszy wiersz
a[1:,:] # od drugiego wiersza w dol
a[:,1:] # od drugiej kolumny w dol
a[:,a.shape[1]-1 ] # ostatnia kolumna
a[a.shape[0]-1, : ] # ostatni wiersz

```


Macierze wielowymiarowe
```{python}

# tworze macierz o wymiarach 2x2x2
a = np.array([[1,2],[3,4]],[[5,6],[7,8]])



# dołożenie nowych wymiarow powoduje ze dostajemy kolejny ineks. Kolejny indeks jest dokladany z lewej strony (po zobaczeniu przykadlwo zrozumiesz o co chodzi zo dokladaniem po lewej:

# mamy jeden wymiar
a=np.array([1,2,3])
a[2] # dostaje drugi element (druga kolumna jezeli traktowa to jako macierz o wymiarach 1X3)

# dokladam wymiar drugi
a=np.array([[1,2,3], [3,4,5]])
a[3,2] # wartosc 2 odwoluje sie dalej do drugiej KOLUMNY (ale jest to juz nie wymiar o indeksie 0 ale wymiar o indeksie 1, bo zostal przesuniety w prawo). Nowy wymiar jest po lewej stronie i on leci po nowym wymiarze o indeksie 1 (wiersze)

# dokladam trzeci wymiar
a=np.array([[[1,2,3], [3,4,5]], [[6,7,8],[9,10,11]]])
a[1,3,2] # nowy wymiar (plastry trojwymiarowej macierzy) jest dolozony po lewej stronie (w przykladnie wartosc 1)


# graficzne podsumowanie tej logiki wymiarow na rysunku:
https://www.google.com/search?q=numpy+array&tbm=isch&source=iu&ictx=1&fir=uiZt51tvuJE1PM%253A%252C1A3kHFAoV2Q2XM%252C_&vet=1&usg=AI4_-kRLpak4KNy8fqWXrsph4EYf_EkHPQ&sa=X&ved=2ahUKEwi-7frq4PziAhWR7KYKHdw9BeIQ9QEwAHoECAIQAw#imgrc=3MW07qtoURqTWM:&vet=1


# przyklady uzywanie powyzszej reguly (Asiu, ja tak na 90% jestem pewien poprawnosci ponizszego nazewnictwa :). Zaladam ze nowy (trzeci) wymiar doklada plasterki w dol (jak warstwy na torcie), a nie w tyl (jak ksiazki na polce) )
a[:,:,2] # tyl macierzy
a[:,:,0] # czolo macierzy
a[0:,:,:] # dach macierzy (gorny plaster)
a[2:,:,:] # spod macierzy (dolny plaster)
a[:,0,:] # bok macierzy (lewy)
a[:,2,:] # bok macierzy (prawy)



```


### filtrowanie

```{python}

a = np.array([[1,2,3],[4,5,6]])

a[np.where(a>2)] # wartosci wieksze od 2. Macierz nie jest juz kwadratowa tylo jest wektorem.
 
a.diagonal() # elementy diagonalne
 
```




### aktualizacja wartosci

Aktualizajca po indeksach
```{python}

a = np.array([[1,2,3],[4,5,6]])
a[:,1] = np.array([10,20]) # zmieniam druga kolumne
a

a = np.array([[1,2,3],[4,5,6]])


```


Aktualizacja po warunkach
```{python}

a = np.array([[1,2,3],[4,5,6]])
np.where(a > 3, a, 20) # przypisujemy wartosc 20 dla elementow '>3'

```


### usuwanie


```{python}

a=np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
a

# usuwanie elementow tak zeby zachowac ksztalt macierzy (wycinamy cale plastry)
np.delete(arr=a, obj=(1), axis= 0) # dla wymiaru 0 wycinam dla niego wszytko co ma indeks 1.
np.delete(arr=a, obj=(0,1), axis= 1) # dla wymiaru 1 wycinam dla niego wszytko co ma indeks 0 i 1.
np.delete(arr=a, obj=np.s_[0:1], axis= 1) #to co linijka wyzej ale skladnia umowliziwajace poslugowaniem sie logika indeksow przy definiowaniu elementow do usuniecie


```

usuwanie elementow po warunkach

```{python}

a=np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
np.extract(a>3, a) # wyciagniecie elementow '>3'

```




### zmiana kszatłtu i transpozycja

Transpozycja
```{python}

#(1) transpozycja macierzy kwadratowej
a = np.array([[1,2],[3,4]]) 
a.transpose()


#(2) transpozycja macierzy wielowymiarowych
a=np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
a
np.transpose(a, axes=(1,0,2) ) # wymiary teraz maja byc w kolejnosci: wymiar pierwszy jako drugi, drugi jako pierwszy, a trzeci zostaje na swoim miejscu

```


Zmiana ksztaltu
```{python}

# macierz o wymiarach 2x6 (2 wiersze , 6 kolumn)
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a
a.shape

# podstawowy reshape
a1 = a.reshape((6,2)) # zmiana wymiarow z 6x2 na 2x6.
a1
a1.shape 


# reshape z innych schematem kolejnosci elementow
a2 = a.reshape((6,2), order='F') # zmiana wymiarow z 6x2 na 2x6. Ale tutaj otrzymujemy inna kolejnosc elementow. W pierwszym wierszu mamy element w pierwszy pierwszego starego wiersza i element pierwszy drugiego starego wiersza
a2
a2.shape 

```


Dodanie wymiaru

```{python}

a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

# dodanie dwóch kolejnych wymiarow
a = np.expand_dims(a = a, axis = 0) # dodaje pierwszy wymiar
a = np.expand_dims(a = a, axis = 0) # dodaje drugi wymiar

```



### bindowanie array

```{python}

import numpy as np

# (1) przyklad macierzy dwuwymiarowych

# doklejenie do macierzy 2X3 nastepnej macierzy 2X2
a1=np.array([[1,2,3], [3,4,5]])
a2=np.array([[10,20,30], [30,40,50]])

np.append(a1, a2, axis=0) # sklejenie maciarzy jedna pod druga
np.append(a1, a2, axis=1) # sklejenie maciarzy jedna obok drugie



#(3) Macierze wielowymiarowe


a1 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) # macierz 2x2X2
a2 = np.array([[10,20],[30,40]]) # macierz 2X2 (plaserek w przestrzni trojwymiarowe)

# macierz a2 ma za malo wymiarow (dwa, a macierz a1 ma trzy. Musimy zrobic plasterek 2X2 z trzecim wymiarem (dodobic 3 indeks)
a3 = a2.reshape((1,2,2))


np.append(a1, a3, axis = 0) # doklejenie w dol

np.append(a1, a3, axis = 1) # doklejenie w bok - tutaj blad bo nie pasuja rozmary
np.append(a1, a3.transpose((1,0,2)), axis = 1) # doklejenie w bok - teraz pasuje bo odopowiednie przetransponowalismy doklejany do macirzy a1 plasterek a3

np.append(a1, a3, axis = 2) # doklejenie w tyl - ale znowu blad
np.append(a1, a3.transpose((1,2,0)), axis = 2) # doklejenie w tyl - teraz pasuje bo odopowiednie przetransponowalismy doklejany do macirzy a1 plasterek a3

# przy dokleaniu ponuje mniej wiecej taka zasada zgocnosci wymiarow:
# jezeli sklejam po wymiarze axis - n to dla pozostalych wymiarow roznych od n musi zachodzic zgodnosc rozmarow


```




Przykład dopasowywania rozmarow macierzy i roznej wymiarowosci przy bindowaniu

```{python}
# tworze macierz dwuwymiarową

matrix = np.array([[1,2,3],[10,20,30],[40,50,60]])

# wyciągam przekątną macierzy
np.diag(matrix)

# dziele sumy kolumnowe i wierszowe przez przekątną
s_c = np.around(np.diag(matrix)/np.sum(matrix, axis = 0)*100, 2)
s_r = np.around(np.diag(matrix)/np.sum(matrix, axis = 1)*100, 2)

# chce powyższy wynik zbindować z macierzą dwuwymiarową, więc używają funkcji resphape muszę dodać do tych jednowymiarowych macierzy sztucznie drugi wymiar
s_c = np.reshape(a=s_c, newshape=(s_c.shape[0],1)) 
s_r = np.reshape(a=s_r, newshape=(1,s_c.shape[0])) # alternatywnie: s_r = np.array([s_r])

# do wyniku kolumnowego dodaje brak danych. Ale zapisuje do jako [[np.na]] po to żeby był dwuwymiarowy
s_c = np.append(s_c, [[np.nan]], axis=0)

# teraz mogę dobindować wynik 
matrix_1=np.append(matrix,   s_r, axis = 0)
matrix_2=np.append(matrix_1, s_c, axis = 1)

```



### bindowanie array z listy

```{python}

import numpy as np

# niestety niedodaje dodatkowegy wymiaru. Bindowac mozna tylko po istniejacych wymiarach
np.concatenate(arrays_list, axis = 0)

# mozna bindowac po dodatkowym wymiarze
np.stack(arrays_list, axis = 0)

```



### operacje na kilku macierzach zwracajece jedna macierz

```{python}

a1 = np.array([[1,2],[3,4]])
a2 = np.array([10,20])

a1 + a2 # wektor a2 jest dodawany do kazdego wiersza macierzy a1

a1 * a2  # kolejne elementy kazdego wiersza a2 sa mnozone przez kolejne elementy wektora  a1


```




### sortowanie


```{python}

a1 = np.array([[7,5,3,6],[3,2,4,5]])

a1[np.argsort(a1[:, 0]),:] # po sortowanie po pierwszej kolumnnie

a1[:,np.argsort(a1[0, :])] # po sortowanie po pierwszym wierszu

```


### funkcje na macierzach

```{python}

a1 = np.array([[1,2],[3,4]])

a1.sum() # suma wszystkich elementow
a1.sum(axis=1) # suma po wymiarze 1

np.apply_over_axes(np.sum, a1, [0]) # sum w po wierszach (w dol)
np.apply_over_axes(np.sum, a1, [1]) # sum w po kolumnach (w prawo)

np.apply_over_axes(func=lambda x, y: np.sum(x,y) , a=a1, axes=[1]) # to co linijke wyzej ale z uzyciem skladni funkcji anominowej. Do lambdy przekazalem argument x (kolejne wiersze) i y (axes - osie po ktorych ma byc sumowanie)

np.apply_over_axes(func=lambda x, y: np.sum(x**2,y) , a=a1, axes=[1]) # sumuje po kolumnach, ale dodatkowo kazdy element podnosze do kwadratu



a2 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) # macierz 2x2X2
np.apply_over_axes(func=lambda x, y: np.sum(x**2,y) , a=a2, axes=[1]) # sumowanie po jednym wymiarze macierzy trojwymiarowej
np.apply_over_axes(func=lambda x, y: np.sum(x**2,y) , a=a2, axes=[0,1]) # sumowanie po dwoch wymiarach macierzy trojwymiarowej


```



### braki danych i wartosci nieskonczone

```{python}

import numpy as np

a = np.array([[1, np.inf, 10], [3, np.nan, np.inf]]) # macierz z wartoscia nieskonczona i brakami danych

a[np.isinf(a)]  = -10 # zamiana wartosci nieskonczonych na -10
a[np.isnan(a)] = -1 # zamiana brakow danych na -1


a = np.array([[1,np.inf,10],[3,np.nan, np.inf]]) # macierz z wartoscia nieskonczona i brakami danych
a[1, np.isinf(a)[1,]] = -10 # zamiana na 10 wartosci nieskonczonych w drugi wierszu
a


```




### rozne funkcje i triki

```{python}

a = np.array([[1,2],[3,4]])
a+1 # dodanie do wszystkich elementow wartosci 1
a*10 # pomnozenie wszystkich elementow przez wartosci 10

# UWAGA przypominam ze w przypadku np. list powyzsza skladania daje inne rezultaty: '+ 1' oznacza doklejenie elementu '1',a  '* 10' oznacza zwrocenie listy 10 razy:
lista = [1,2,3,4]
lista + [1]
lista * 10


a = np.array([[1,7],[3,4]])
a.argmin(axis=0) # pozycja najmiejszego elementu dla kazdej kolumny
a.argmin(axis=1) # pozycja najmiejszego elementu dla kazdego wiersza

a.argmax(axis=0) # pozycja najwiekszego elementu dla kazdej kolumny


```





## Scipy




