--- 
title: "Introduction to Python"
author: "Łukasz Muszyński"
date: "`r Sys.Date()`"
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: ""
---

# INTRO

Placeholder



<!--chapter:end:index.Rmd-->


# (PART) <lfg>PROGRAMMING</lfg> {-} 

Placeholder


## operatory logiczne
## podstawowe komendy i funkcje
### sprawdzenie typu obiektu
### inne komendy i funkcje
## control flow
### if else
### petla 'for'
#### Podstawowy for
#### For w listach
#### For iterujace po kilku listach rownolegle
### petla 'while'
## Indicies
## shallow and deep copies
## generators
## dynamic code
## errors and warning
### try
### assertion

<!--chapter:end:1_01_PROGRAMING_syntax_base.Rmd-->


# FUNCTIONS AND ENVIROMENTS

Placeholder


## podstawowa składnia
## przekazywanie argumentow przez wartosc a przekazywanie przez referencje
## funkcje anonimowe 
## programowanie funkcyjne
## wektoryzacja funkcji
## rekurencja
## zakres istnienia zmiennych (scoping rules)
## dekoratory
## Przydatne 

<!--chapter:end:1_02_PROGRAMING_functions_and_environments.Rmd-->


# DATA TYPES

Placeholder


## liczby
### tworzenie
### Ciagi
### rozne funkcje
## tekst
### tworzenie statyczne
### Tworzenie dynamiczne - nowa skladnia z funkcja 'format'
### Formatowanie wygladu-skladnia
#### tekst
#### liczby
### Tworzenie dynamiczne - stara skladnia
### multiline string
### odwolywanie sie do podstringow
### szukanie pozycji podstringow
### modyfikacja 
### inne przydatne triki
### rozne podstawowe operacje i funkcje zwiazane ze stringami
### encode i decode
## wyrazenie regularne
## daty
### tworzenie dat
### atrybuty daty
### inkrementacja daty
### roznice dat
### zmiana wartosci
### zaokraglanie dat
### generowanie ciagu dat

<!--chapter:end:1_03_PROGRAMING_data_types.Rmd-->


# DATA STRUCTURES - basic

Placeholder


## listy
### atrybuty listy
### tworzenie listy
### dodawanie wartosci
### aktualizacja wartosci
### splaszczanie (flattening)
### usuwanie 
### filtrowanie
### wyszukiwanie indeksu
### sortowanie
### operowanie funkcjami na elementach
### ciekawe operacje i triki na listach
### losowe elementy
## slowniki
### tworzenie
### odwolywanie sie do elementow
### updating and adding
### removing
### filtering
### filtrowanie kluczy po liscie
### filtrowanie wartosci po liscie
### for jednolinijkowy
## tuples
### atrybuty
### tworzenie
### odwolywanie sie do elementow
## set (zbiory)
### tworzenie
### atrubyty
### aktualizacja/dodawanie/usuwanie/filtrowanie wartosci
### funkcje na elementach
### operacje na zbiorach

<!--chapter:end:1_04_PROGRAMING_data_structures-basic.Rmd-->


# DATA STRUCTURES-Pandas

Placeholder


## Series
### tworzenie
### atrybuty
### indeksy
#### tworzenie indeksow i odwolywanie sie do elementow przez nie
#### Indeksy przy sklejaniu elementow
### Aktualizacja wartosci 
### sortowanie
### rozne funkcje
### praca z brakami danych i wartosciami nieskonczonymi
## Categorical
### Tworzenie
### usuwanie/dodawanie/modyfikacje kategorii
### dodawanie nowych elemntow
## DATA FRAMES
### Najważniejsze atrybuty DataFrame
### Tworzenie ramki danych
### Konwersja ramki danych na inne typy
### Indeksy
#### Tworzenie multiindeksow wierszowych
#### Sklejanie multiindeksow
#### Przydane funkcje
### Wymuszanie typów kolumn w DataFrame
### Zmiana nazw kolumn
### Usuwanie kolumn
###  Filtrowanie Data Frame - wybieranie kolumn
### Filtrowanie Data Frame - wybieranie wierszy
### Dodawanie nowych kolumn
### Operatory wyciaganie danych z kolumn
### Aktualizacja wartosci w kolumnach
### Sortowanie
### Bindowanie - w wierszach
### Bindowanie - w kolumnach
### Łączenie - merge
### Problemy z danymi
#### Duplikaty
#### Braki danych
#### Nieskonczone wartosci
### Funkcje oknowe
### Praca z GroupBy
### Funkcje po kolumnach i wierszach
#### apply
#### operacje na wszystkich elementach
#### operacje wzdloz osi
#### lambda-przyklady
#### problem zwracania wektorow przez operacja
### Praca z tekstem
### Praca z datami
### Dummy - rekodowanie na zmienne zero-jedynkowe
### crosstab - analiza liczebnosci 
### zmiana struktury DataFrame
#### Transpozycja
#### melt/pivot
#### unstack-melt
#### pivot_table
### Rozne problemy 
#### Losowanie coraz mniejszych zakresow
#### Uzupelnianych kategorii
#### Sklejanie stringow

<!--chapter:end:1_05_PROGRAMING_data_structures-Pandas.Rmd-->


# DATA STRUCTURES - Numpy, Scipy

Placeholder


## Numpy
### Tworzenie
### atrybuty
### odwolywanie sie przez indeksy
### filtrowanie
### aktualizacja wartosci
### usuwanie
### zmiana kszatłtu i transpozycja
### bindowanie array
### bindowanie array z listy
### operacje na kilku macierzach zwracajece jedna macierz
### sortowanie
### funkcje na macierzach
### braki danych i wartosci nieskonczone
### rozne funkcje i triki
## Scipy

<!--chapter:end:1_06_PROGRAMING_data_structures-Numpy_Scipy.Rmd-->

# DATA STRUCTURES - other

<!--chapter:end:1_07_PROGRAMING_data_structures-other.Rmd-->


# DATA STRUCTURES - objective programing

Placeholder


## Tworzenie klasy i obiektow
## Atrybuty
## Metody
## Prywatne atrybuty i metody
## Metody statyczne
## mechanizm dziedziczenia
### tworzenie podklas
### przeciazanie metod
### funkcja 'super'

<!--chapter:end:1_08_PROGRAMING_data_structures-objective_programing.Rmd-->


# WORK ORGANISATION

Placeholder


## importowanie pakietow/modulow
## Wlasne moduly i pakiety
### Wlasny modul
### Wlasny pakiet - wersja uproszczona
### Wlasny pakiet wg. standardu pip
## Tworzenie wirtualnych srodowisk

<!--chapter:end:1_09_PROGRAMNG_work_organisation.Rmd-->


# DATA IMPORT AND EXPORT

Placeholder


## pickles
## csv / txt
### Import 
### Eksport
## excel
### Import 
### Eksport
## schowek
## dates parser

<!--chapter:end:1_10_PROGRAMING_data_import_export.Rmd-->

# TOOLS AND TRICKS



## praca z katalogami i plikami

[Working With Files in Python](https://realpython.com/working-with-files-in-python/)

Wyswietlanie zawartosci katalogu 
```{python}
import os


# istnienie sciezek
os.path.exists('...') # Returns True if path or directory does exists.
os.path.isfile('...') # Returns True if path is File.
os.path.isdir('...') # Returns True if path is Directory.



# wszystkie pliki i katalogi w podanej sciezce
os.listdir(path = 'C:/Users/memy/OneDrive/Pulpit/1_Programs_and_programing/R/1.MANUAL_R/')


# wszystkie pliki i katalogi w podanej sciezce z podana pelna sciezka
import glob
z=glob.glob('C:/Users/memy/OneDrive/Pulpit/1_Programs_and_programing/R/1.MANUAL_R/*.*')
z

# wszystkie pliki i katalogi w podanej sciezce (inna skladnia)
for entry in os.scandir('C:/Users/memy/OneDrive/Pulpit/1_Programs_and_programing/R/1.MANUAL_R/'):
    print(entry.name)




# same katalogi
 for entry in os.scandir(path):
    if entry.is_dir():
      print(entry.name)


# same pliki 
 for entry in os.scandir(path):
    if entry.is_file():
      print(entry.name)


# same pliki o rozszerzeniu .rmd
import os
import glob
paths = glob.glob('C:/Users/memy/OneDrive/Pulpit/1_Programs_and_programing/R/1.MANUAL_R//*.rmd')

# z powyzszego wyciagam same nazwy plikow (usuwam sciezke) w wersji z rozszerzeniami i bez rozszerzen
files_names = []
files_names_no_extensions = []
for p in paths:
  full_path = os.path.basename(p)
  files_names= files_names + [full_path]
  files_names_no_extensions = files_names_no_extensions + [os.path.splitext(full_path)[0]]

files_names
files_names_no_extensions

```




Tworzenie katalogu
```{python}

# tworzenie katalogu
os.mkdir(path)

```


Usuwanie pliku lub katalogu
```{python}

# kasowanie katalogu
os.rmdir(path)


# katowanie katalogu z wszystkimi podkatalogami
import shutil
shutil.rmtree(path)

```






Przenoszenie pliku lub katalogu
```{python}

# przenoszenie pliku/katalogu (https://www.techbeamers.com/python-copy-file/)
import shutil
shutil.copy(file, descination)

# kopiowanie z proba zachowania metadanych pliku
shutil.copy2(file, descination)

```






## Podstawowe polecenia w konsoli



### Conda

Uwagi o konfiguracji condy: <br> 
W Menu Start powinien być bezpośredni dostęp do pliku `Configuration.Ink`.


**Pakiety**
```{python}

# instalacja pakietu
conda install nazwa_pakietu

# odinstalowanie pakietu
conda uninstall nazwa_pakietu

```


**Praca ze srodowiskiem wirtualnym**
```{python}

# uworzenie nowego srodowiska wirtualnego
conda create --name nazwa_srodowiska

# uworzenie nowego srodowiska wirtualnego zadaniem wersji pythona
conda create --name nazwa_srodowiska python=3.8


# lista srodowiska wirtualnych
conda env list  

# usuwanie wirtualnego srodowiska
conda env remove nazwa srodowiska


# aktywowanie srodowiska 
conda activate nazwa_srodowiska

# dezaktywacja srodowiska
deactivate

```






### Python/pip

Przydatne funkcje wywolywane w konsoli (nie jest to kod Pythonowy!!!). Konsola to wiersz polecen w Windowsie. Uwaga, żeby nie było żadnych nieprzewidzianych konfliktow, to przed rozpoczeciem pracy z konsoli najlepiej wywolac srowowisko pythonowe w ktorym chcemy pracowac. 


```{python}

# jeszcze RAZ PRZYPOMINAM: ponizszy kod to nie jest kod pythona. Wykonujemy go w wierszu poleceń a nie w narzędziu do programowania w pythonie.

# Lista zainstalowanych pakietow w srodowisku w ktorym aktualnie pracujemy
pip list

# ograniczam liste do pakietow ktore maja w nazwie string "pandas'
pip list | findstr pandas


# lista pakietow ktore nie sa najnowszymi wersjami (warto sprawdzic czy nie warto dla nich zrobic aktualizacji)
pip list --outdated 


# lista pakietow ktore sa najmowyszymi wersjami
pip list --uptodated 

# instalacja pakietu pillow w najnowszej dostepnej wersji
pip install pillow

# upgrade zainstalowanego pakietu  pillow do najnowszej wersji
pip install --upgrade pillow

# instalacja pakietu 'pillow', ale o konkretnym numerze wersji
pip install pillow==5.2.0
pip install pillow>=5.1.0,<5.3.0 # mozemy tez uzywac znakow nierownosci przy podawaniu wersji


# wymuszenie reinstalacji pakietu 'pillow'
pip install --upgrade --force-reinstall pillow


# wymuszenie reinstalacji pakietu 'pillow' ale bez wymuszania reinstalacja pakietow ktore sa zalezne
pip install --upgrade --no-deps --force-reinstall <packagename>

# instalacja pakietow ktore sa na liscie w pliku teksowym 'requirements.txt'
pip install -r requirements.txt


# wyszukanie informacji o okreslonym pakiecie w srodowisku w ktorym pracujemy
pip search pandas

# odinstalowanie pakietu 'pandas'
pip uninstall pandas


# uruchomienie skryptu pythonowego 'main_program' w konsoli (wiecej o uruchamianu kod w konsoli w innych czesciach manuala)
python main_program.py


# uruchomienie polecania pythonowego bez uruchamiania konsoli
python -c "import sys; print('rob')"


# zrzucenie do pliku 'requirements.txt' zainstalowanych pakietow
pip freeze requirements.txt
pip freeze > requirements.txt # nie wiem co daje znak '>' ale taka jest oficjalna skladnia.

```

## python

Ponizsze kody sa juz Pythonowe

```{python}

import os

# working directory - bieżący roboczy katalog
print(os.getcwd())


# pelna sciezka do katalogu
os.path.abspath("") # teraz dostane pelna sciezke katalogu w ktorym pracuje (working directory)
os.path.abspath("../") # co co wyzej ale jeden katalog w gore
os.path.abspath("../../") # co co wyzej ale dwa katalogi w gore
os.path.abspath("output.xlsx") # pelna sciezka do pliku 'output' w katalogu roboczym


# environmental variables (lisa zmiennych srodowiskowych w Windowsie)
os.get_exec_path()


# check if Python environment exists
import os

if os.getenv('VIRTUAL_ENV'): # provide environment name you are looking for
    print('Using Virtualenv')
else:
    print('Not using Virtualenv')



# run commans in the shell
os.system(r"\\spplfapcen02\userdata\UN99LT\Desktop\smietnik\klienci.xlsx") # remember about letter "r"  at the beginning


# lista zaladowanych modulow
import sys
sys.modules.keys()
print('\n'.join(sys.modules.keys())) # ladniejszy sposob wyswieltenie wynikow
list(filter(lambda x: x.find('pandas')>-1 ,t1)) # lista modulow dot. pakietu 'pandas'


```


## pomiar czasu wykonania kodu

```{python}

import time
start = time.time() # rozpoczecie pomiaru czasu

# przetestujemy czas wykonania petli
a = range(100000)
b = []
for i in a:
    b.append(i*2)
    
end = time.time() # zakonczenie pomiaru czasu
print(end - start) # czasy wykonania jako roznica uzyskanych czasow (w sekundach)
print((end - start)/60) #  (w minutach)
print((end - start)/3600) #  (w godzinach)

```




## main i parametryzacja z konsoli

### Prosty przyklad

Uruchamianie pliku w konsoli z parametrami
```{pyhon}
python test.py arg1 arg2
```

Plik obsugujacy pobieranie parametrow
```{python}

import sys

def hello(a,b):
    print "hello and that's your sum:", a + b

if __name__ == "__main__": # ten warunke oznacza ze kod w tym warunku jest wykonywany tylko wtedy kiedy skrypt jest uruchamiany z konsoli
    # pobieranie parametrow z konsoli
    a = int(sys.argv[1]) # od 1 bo 0 to nazwa pliku
    b = int(sys.argv[2])
    hello(a, b)

```

### Uzycie parsowania

Uruchamiam plik podajac dwa argumenty i ich wartosci 
```{python}
python add_numbers.py -a 3 -b 8

```

Skrypt:
```{python}

import getopt
import sys

# pobranie wszystkich parametrow z wjatkiem nazwy pliku
argv = sys.argv[1:]
sum = 0

try:
    # parsowanie parametrow
    opts, args = getopt.getopt(argv, 'a:b:', ['foperand', 'soperand'])
    # Check if the options' length is 2 (can be enhanced)
    if len(opts) == 0 and len(opts) > 2:
      print ('usage: add.py -a <first_operand> -b <second_operand>') # komunikat w konsoli jezeli zle podany parametry
    else:
      # Iterate the options and get the corresponding values
      for opt, arg in opts:
         sum += int(arg)
      print('Sum is {}'.format(sum))

except getopt.GetoptError:
    # Print something useful
    print ('usage: add.py -a <first_operand> -b <second_operand>')
    sys.exit(2)


```


## Rozne



### CMD

Uruchamianie polecen z poziomu Pythona w konsoli CMD
```{pythn}
# wykonanie polecenia w cmd
import os 
os.system('pip freeze')


# usuchomienie pliku exe
import subprocess
subprocess.call(['C:\\Program Files\\RStudio\\bin\\rstudio.exe'])

```


### Podglad kodu funkcji
```{python}

import inspect
lines = inspect.getsource(res.plot)
print(lines)

```



### Realtive paths

Mam problem chce uruchomic z konsoli cmd plik Pythonowo v_envem tak zeby nie bylo problemu z ladowaniem wlasnych modulow w katalogach
Zalozny ze mamy struktura katalogow:

Projekt
  \main.py
  \modules
    \__init__.py
    \function_1.py
    \function_1.py
  \venv
  
Uruchamiany plik musi byc w glownym katalogu tak jak tutaj 'main.py'. Po uruchomieniu venv-a odpadam go (dla uproszczenia w venv ustawiam sie w katalogu gdzie jest plik 'main.py')










<!--chapter:end:1_11_PROGRAMING_tools_and_tricks.Rmd-->


# (PART) <lfg>VISUALISATION</lfg> {-} 

Placeholder


## matplotlib
## seaborn
## plotly
## bokeh
## plotnine

<!--chapter:end:2_01_VISUALISATION_big_packages.Rmd-->

# other packages

<!--chapter:end:2_02_VISUALISTAION_other_packages.Rmd-->

# graphs

<!--chapter:end:2_03_VISUALISATION_graph.Rmd-->

# maps

<!--chapter:end:2_04_VISUALISATION_maps.Rmd-->

# other issues

<!--chapter:end:2_05_VISUALISATION_othes_issues.Rmd-->


# (PART) <lfg>PROGRAMMING</lfg> {-} 

Placeholder


## Relational databases
### SQL Server
### Postgres
### Oracle
### MySql
## Norelational databases
### Neo4j
### Redis
### MongoDB
## R
## pyspark

<!--chapter:end:3_01_ADDS_ON_cooperation_with_other_tools.Rmd-->



## Linter
## AirFlow
## Luigi
## Selenium
## Flask
## Django
## Jupyterbook

<!--chapter:end:3_02_ADDS_ON_other.Rmd-->

# (PART) <lfg>APPENDICIES</lfg> {-} 



# good habits

<!--chapter:end:4_01_APPENDICIES_good_habits.Rmd-->


# IDE

Placeholder


## Jupiter Notebook
### Installation
### Connecting with Venv
### Magic commends
### Global settings
### Converting to different formats
### widgets 
### debuggowanie
## Jupiter Lab
### Installation
## PyCharm
### Konfiguracja Git i GitHub
### Dodanie Git do istniejącego projektu
### Zmiana skrotow
### Podpinanie do vevn
### Ustawienia globalne a ustawienia projektu
### Uzyteczne skroty
### Srodowiska w linuxie:
### debuggowanie
## Rstudio

<!--chapter:end:4_02_APPENDICIES_IDE.Rmd-->

# Installation


## Anaconda

Anaconda domyślnie się zazywczaj instaluje na C:\Users\NazwaUsera\Anaconda\

Po zainstalowaniu należy sprawdzić czy w Widowsie do zmiennych środowiskowych 'paths' są dodane 3 ścieżki w ramach katalogu Anacondy:

* C:\Users\NazwaUsera\Anaconda\
* C:\Users\NazwaUsera\Anaconda\Scripts
* C:\Users\NazwaUsera\Anaconda\bin   # bez tego nie bedzie działał poprawnie 'pip'

<!--chapter:end:4_03_APPENDICIES_Installation.Rmd-->

--- 
title: "Introduction to R"
author: "Łukasz Muszyński"
date: "`r Sys.Date()`"
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: ""
---
--- 
title: "Introduction to R"
author: "Łukasz Muszyński"
date: "`r Sys.Date()`"
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: ""
---

# INTRO

<!--chapter:end:bookdown-Manual_Python.Rmd-->

